### ISSUE TITLE
Clarify use of the term "permission group" ?

### ISSUE THREAD

**Issue by CrookedNumber** [publicmediaplatform/pmp-issues#16]
While writing a module that adds permissions to a Drupal node pushed up to the PMP, I *think* found some slightly confusing docs.

https://github.com/publicmediaplatform/pmpdocs/wiki/Permission-Group-Profile

This page talks a lot about "permissions groups", but unless I'm mistaken, a group is just a collection of orgs. It could have any purpose for its creation and, in and of itself, it has nothing explicitly to do with permissions.

Though it appears that "permission group" is the accepted term in the spec (see: http://cdoc.io/spec.html#role-based-security)

Assuming I'm correct, maybe we (or *I*) should add a clarifier like:

>Permission Groups are groups (i.e., docs where profile = group) that are used to implement PMP's Role-based content rights management system. Note that  group is merely a collection of orgs, and can be created for a variety of purposes. In and of itself, a group has no explicit relation to permissions.

Yeah?

**Comment by cavis** [comment]
Calling this closed.  FWIW, we generally advertise the "permissions" aspect of groups to PMP clients (Wordpress/Drupal/etc admins).  To avoid confusion!
