### ISSUE TITLE
use Prefer header to indicate size of desired response

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-issues#26]
See publicmediaplatform/pmpcode#89

> Via Irakli on pmp-dev list:
> 
> there’s a draft specification in HTTP that allows standards-compliant way of implementing such semantics. It’s HTTP Prefer header:
> 
> http://tools.ietf.org/html/draft-snell-http-prefer-18
> 
> So you could request minimal response by saying something like:
> 
> Prefer: responsePayloadSize=min
> Vary: Prefer, Accept, Accept-Encoding
> 
> Or if you decide you want to indicate specific fields instead, it can also be supported:
> 
> Prefer: responseFields=title,author,bio
> Vary: Prefer, Accept, Accept-Encoding
> 
> Please note that the name of the prefer field (“responsePayloadSize”, “responseFields”) is an extension and would need to be documented in PMP spec. Also server will have to include the “Prefer” field in the Vary response header to make sure caching on the client side and in proxies happens correctly.

**Comment by cavis** [comment]
Moving this out of the backlog.  And adding to it:

1. Gzip support!

**Comment by cavis** [comment]
Turns out the PMP already supported Gzip - so I added some explicit tests for it.  And set the minimum-gzip threshold to 800 bytes, for now.

Implemented smaller-response payloads as follows:

1. Default request (no preference specified)
  * Response header `Vary: Prefer, Accept-Encoding`
  * Will include the full payload with static links
2. Request with header `Prefer: return=minimal`
  * Response header `Vary: Prefer, Accept-Encoding`
  * Response header `Preference-Applied: return=minimal`
  * Includes a minimal payload, with NO static links

Will add to PMP docs and start incorporating this into the SDK's sometime after this gets to production.

**Comment by cavis** [comment]
Deployed to sandbox.

**Comment by cavis** [comment]
Deployed to production.

**Comment by cavis** [comment]
Err... still need to document this, though.  And incorporate into some more SDKs.

**Comment by cavis** [comment]
This made it into the docs - https://support.pmp.io/docs#collection-docjson-headers

**Comment by kookster** [comment]
nice docs.
