### ISSUE TITLE
Signature mismatch for notifications with non-ascii characters

### ISSUE THREAD

**Issue by laurafeier** [publicmediaplatform/pmp-issues#49]
This happens for subscriptions with secret keys. It appears that header X-Hub-Signature has different value than expected when feeds have non-ascii characters.

For example:
```
crypto = require('crypto');
var secret = 'secret';
// feed with unicode data
var feed_body = '<?xml version="1.0" encoding="UTF-8"?><rss ...> ... \u2014 ... </rss>';
var hmac_sent = crypto.createHmac('sha1', secret).update(feed_body).digest('hex');
// subscriber expects signature from utf-8 data
var hmac_expected = crypto.createHmac('sha1', secret).update(feed_body, 'utf-8').digest('hex');
```

It looks like <a href="https://github.com/joyent/node/blob/master/lib/crypto.js#L117">`update(data, encoding)`</a> uses DEFAULT_ENCODING when encoding is not specified. DEFAULT_ENCODING appears to be <a href="https://github.com/joyent/node/blob/885f72105bf0b18007100550f131c85ca56536e0/lib/crypto.js#L25">`buffer`</a> which will make 'binary' the encoding used by `update`. From <a href="http://nodejs.org/api/buffer.html#buffer_buffer">nodejs docs</a> it looks like 'binary' encoding preserves only the first 8 bits from a character. This means that utf8 characters represented in more than one byte will get transformed into a different characters. When generating the hmac without the encoding specified, the hmac will actually be generated from a different content when such characters are present in the feed body.

**Comment by cavis** [comment]
Gotcha.  So a simple `.update(data, 'utf8')` should fix it, right?  As in publicmediaplatform/pmpcode#135.

**Comment by laurafeier** [comment]
Yes, looks good.

**Comment by cavis** [comment]
Alright, this has been merged and deployed to the Sandbox environment.  Do you have code out there that was hitting this bug, where you can verify the fix?

Otherwise, this change is probably minor enough that it can just go out with the next Production release.

**Comment by laurafeier** [comment]
I just tested it. It works. Thanks.

**Comment by cavis** [comment]
Awesome - will cut a release and get this deployed Friday-ish.  (Along with #48).

**Comment by cavis** [comment]
This has been deployed to production.
