### ISSUE TITLE
Links.owner

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-issues#50]
See https://discuss.pmp.io/t/explicitly-setting-links-creator/110

We need a way to publish documents "on behalf of" someone else, in a way that encourages PMP consumers to display the document owner instead of the user that created the doc.

Code changes:

1. Add a links.owner relation to the "core" schema
  * If not explicitly set, defaults to links.creator
  * If you attempt to update links.owner to something blank/empty, it reverts back to links.creator
  * Grants write permission to any linked users
2. Add a ?owner=1234 query parameter
  * Will be the creator, if owner was not set on the document
3. Update support.pmp.io to search/display owners instead of creators

SDK updates:

1. Modify any "creator" involving examples to instead be "owner"
2. Add owner shortcuts to complement any `getCreatorLink()` shortcuts
3. Update any support doc examples involving creators

Documentation:

1. Add docs for `owner` query parameter, link relation, and publisher best practices
2. Make docs more explicit on how the `distributor` link should be used.  (To represent a business relationship).  Maybe combine a section on creator/owner/distributor links.
3. Add support docs on permission links

**Comment by cavis** [comment]
Deployed!  But still have some TODOs here.

**Comment by cavis** [comment]
Is now described in the support docs -> https://support.pmp.io/docs#collection-docjson-core-links.  And built into the PHPSDK.

TODO:

- [ ] Update display/search on support searcher
- [ ] Update display/search on wordpress plugin
- [ ] Open a ticket to fix display/search in the drupal plugin
- [ ] Build more prominently into the js sdk

**Comment by kookster** [comment]
I should start using this on the importer:
https://github.com/PRX/pmp-importer.prx.org/issues/14
