### ISSUE TITLE
Duplicate query parameters

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-issues#61]
Querying for `?itag=foo&itag=bar` results in a 500.  As it's trying to split a string by `,` or `;`, and instead gets an array.

Should probably treat as `?itag=foo,bar`.

**Comment by ejain** [comment]
Treating `?itag=foo&itag=bar` as `?itag=foo,bar` makes sense to me, since that's how unrelated parameters are handled. But then I'd also expect `?itag=foo;bar&itag=baz;qux` to be handled as `?itag=(foo OR bar) AND (baz OR qux)`. If that's too much trouble, return a 400?

**Comment by cavis** [comment]
Considering implementing this as: `?itag=foo&itag=bar;baz&itag=qux` --> `?itag=foo,bar;baz,qux`.  In other words, any duplicate params will just be joined together with AND `,` ... even if that breaks the current [don't combine AND and OR operators](https://github.com/publicmediaplatform/pmpdocs/wiki/Querying-the-API#boolean-operators) rule.

I'm not sure it's worth the trouble of supporting complex order-of-operation groupings in these filter parameters, right now.  You can already accomplish the same thing by using/abusing the ES query syntax in the `text` parameter:

```
GET docs?text=itag:((foo OR bar) AND (baz OR qux))
```

**Comment by cavis** [comment]
Implemented as above (just dumbly join the 2 strings with an AND `,`).

Deployed to Sandbox!

**Comment by cavis** [comment]
Deployed v0.0.25
