### ISSUE TITLE
Sandbox api gives 401 error

### ISSUE THREAD

**Issue by tim-wgbh** [publicmediaplatform/pmp-issues#69]
I am setting up the Drupal pmpapi module, Drupal 7.41. I have obtained a user GUID, client access and client secret keys. The production endpoint gives no error, but the sandbox endpoint does (see screenshot below).

![screen shot 2015-11-02 at 3 01 20 pm](https://cloud.githubusercontent.com/assets/11877425/10892651/abbd426a-8172-11e5-9909-143c91282d19.png)

**Comment by cavis** [comment]
Are you trying to use the same credentials (client-id/secret) for both Production and Sandbox?

The Prod/Sandbox systems are actually completely separate, so you'll need to generate different credentials for each of them.

**Comment by tim-wgbh** [comment]
I created the credentials and first tried to use them with the sandbox. I got the error immediately.

When I changed the platform to production, I got no error.

In the credential creation process at https://support.pmp.io/credentials, there is no differentiation between sandbox and production.


________________________________
Tim Kinnel, senior developer/architect | WGBH.org
+1 617 300 2594

**Comment by cavis** [comment]
It may be a bit unclear, but you have to log into the support site selecting "api-sandbox" from the dropdown.

![image](https://cloud.githubusercontent.com/assets/1410587/10892887/09b0e9ea-8163-11e5-82d5-8fdcf68b8aeb.png)

You can actually sign into the support site with multiple users/environments.  And pick which one you want to manage via that upper-right dropdown menu.

![image](https://cloud.githubusercontent.com/assets/1410587/10892927/4fb8c016-8163-11e5-9a63-b9e7778351dc.png)

**Comment by tim-wgbh** [comment]
OK gotcha.

I'm only pulling, not pushing - any problem with just sticking with production then?

Thanks.


________________________________
Tim Kinnel, senior developer/architect | WGBH.org
+1 617 300 2594

**Comment by cavis** [comment]
No problems with testing "pull" functionality from production.  There's also less test/dummy data to sift through in prod.

And if you wanted to be totally sure nobody "accidentally" pushes your content, you can create a read-only credential:

![image](https://cloud.githubusercontent.com/assets/1410587/10893080/1ea2cd54-8164-11e5-8317-06e1feadf4b3.png)

**Comment by tim-wgbh** [comment]
Ok thanks. Yes, I'd already done that.

Cheers and thanks for the help.

tk

________________________________
Tim Kinnel, senior developer/architect | WGBH.org
+1 617 300 2594
